# Generated by Django 4.1.4 on 2023-01-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0002_alter_match_date_alter_team_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
